-- Make :Exercism list show exercises in serial learning order with a number and
-- a difficulty marker, so you can work through them 1, 2, 3, … (hello-world →
-- concepts in syllabus order → practice easiest-first).
--
-- We override exercism.main.list_exercises (the plugin offers no hook) and read
-- the ordered data regenerated by scripts/exercism_regen.py into the config repo
-- at ~/.config/nvim/exercism-data. That dir is ours, so plugin updates can never
-- clobber the ordering. Languages we haven't regenerated fall back to the
-- plugin's bundled (unordered) data so every track still opens.
--
-- Note: Exercism enforces unlocking server-side. Following this serial order is
-- what avoids "you haven't unlocked this" errors — concepts come before the
-- practice exercises they gate, so doing them in order keeps the next one open.
local M = {}

local MY_DATA = vim.fn.stdpath("config") .. "/exercism-data"
local REGEN = vim.fn.stdpath("config") .. "/scripts/exercism_regen.py"
local DEFAULT_TRACKS = { "rust", "cpp", "python", "go", "javascript", "typescript", "bash", "haskell" }
local DIFF_ICON = { easy = "🟢", medium = "🟡", hard = "🔴" }

local function plugin_data_dir()
  local ok, lazy = pcall(require, "lazy.core.config")
  if ok and lazy.plugins["exercism.nvim"] then
    return lazy.plugins["exercism.nvim"].dir .. "/data"
  end
  return vim.fn.stdpath("data") .. "/lazy/exercism.nvim/data"
end

-- Ordered list for a language: our regenerated data first, plugin data as fallback.
local function load_exercises(language)
  for _, dir in ipairs({ MY_DATA, plugin_data_dir() }) do
    local path = dir .. "/" .. language .. ".json"
    if vim.fn.filereadable(path) == 1 then
      local ok, data = pcall(vim.fn.json_decode, vim.fn.readfile(path))
      if ok and type(data) == "table" and #data > 0 then
        return data
      end
    end
  end
  return {}
end

local function marker(ex)
  return (ex.difficulty and DIFF_ICON[ex.difficulty]) or "📘" -- 📘 = concept/tutorial
end

--- Install the ordered, numbered picker over the plugin's list_exercises.
function M.patch()
  local ok, main = pcall(require, "exercism.main")
  if not ok then
    return
  end

  main.list_exercises = function(language)
    if language == "" or language == nil then
      language = require("exercism.config").config.default_language
    end

    local exercises = load_exercises(language)
    if #exercises == 0 then
      vim.notify(
        ("exercism: no exercise data for '%s' (try :ExercismRegen %s)"):format(language, language),
        vim.log.levels.WARN
      )
      return
    end

    local items = {}
    for i, ex in ipairs(exercises) do
      items[i] = vim.tbl_extend("force", ex, { idx = i })
    end

    vim.ui.select(items, {
      prompt = "Exercise (" .. language .. ") — serial order",
      format_item = function(ex)
        return ("%3d  %s  %s"):format(ex.idx, marker(ex), ex.name)
      end,
    }, function(choice)
      if choice then
        main.open_exercise(choice.name, language)
      end
    end)
  end
end

--- Regenerate ordered data. With no args, refresh whatever's already generated
--- (or the default track set on first run).
function M.regen(tracks)
  if not tracks or #tracks == 0 then
    tracks = {}
    for _, f in ipairs(vim.fn.glob(MY_DATA .. "/*.json", false, true)) do
      tracks[#tracks + 1] = vim.fn.fnamemodify(f, ":t:r")
    end
    if #tracks == 0 then
      tracks = DEFAULT_TRACKS
    end
  end

  local cmd = { "python3", REGEN, "--out", MY_DATA }
  vim.list_extend(cmd, tracks)
  vim.notify("exercism: regenerating " .. table.concat(tracks, ", ") .. " …", vim.log.levels.INFO)
  vim.system(cmd, { text = true }, function(res)
    vim.schedule(function()
      if res.code == 0 then
        vim.notify("exercism: lists regenerated", vim.log.levels.INFO, { title = "exercism.nvim" })
      else
        vim.notify("exercism regen failed: " .. vim.trim(res.stderr or ""), vim.log.levels.ERROR)
      end
    end)
  end)
end

return M
